---
# 1. התקנת Python ו-venv
- name: Install Python3, pip, and venv
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy Auth project files
  copy:
    src: Auth/
    dest: "{{ app_dir }}/"
    owner: ubuntu
    group: ubuntu
  tags:
      - services
 

- name: Install python packages from requirements.txt
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_command: python3 -m venv


- name: Create .env file for environment variables
  template:
    src: .env.j2
    dest: "{{ app_dir }}/.env"
    owner: ubuntu
    mode: '0600'
  notify: Restart Auth App
  tags:
    - env


- name: Create Systemd service for the Auth app
  template:
    src: auth.service.j2
    dest: /etc/systemd/system/auth.service
  notify: Restart Auth App
  tags:
    - service

- name: Ensure Auth app is running and enabled
  systemd:
    name: auth
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - service